<!-- 47.1 에러 처리의 필요성 -->

<!-- 에러가 발생하지 않는 코드를 작성하는 것은 불가능하다. 따라서 에러는 언제나 발생할 수 있다. 발생한 에러에 대해
대처하지 않고 방치하면 프로그램은 강제 종료 된다.

try...catch 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행시킬 수 있다. -->

<!-- 47.2 try...catch...finally 문 -->

<!-- try...catch...finally 문을 실행하면 먼저 try 코드 블록이 실행된다. 이 때 try 코드 블록에 포함된 문 중에서 에러가
발생하면 발생한 에러는 catch 문의 err 변수에 전달되고 catch 코드 블록이 실행된다. catch 문의 err 변수는 try 코드
블록에 포함된 문 중에서 에러가 발생하면 생성되고 catch 코드 블록에서만 유효하다. finally 코드 블록은 에러 발생과
상관없이 반드시 한 번 실행된다. try...catch...finally 문으로 에러를 처리하면 프로그램이 강제 종료되지 않는다. -->

<!-- 47.3 Error 객체 -->

<!-- Error 생성자 함수는 에러 객체를 생성한다. Error 생성자 함수에는 에러를 상세히 설명하는 에러 메시지를 인수로 전달할
수 있다.

Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖는다. message 프로퍼티의 값은 Error
생성자 함수에 인수로 전달한 에러 메시지이고, stack 프로퍼티의 값은 에러를 발생시킨 콜 스택의 호출 정보를 나타내는
문자열이며 디버깅 목적으로 사용된다.

- Error: 일반적 에러 객체
- SyntaxError: JS 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체
- ReferenceError: 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체
- TypeError: 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체
- RangeError: 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체
- URIError: encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체
- EvalError: eval 함수에서 발생하는 에러 객체 -->

<!-- 47.4 throw 문 -->

<!-- Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 즉, 에러 객체 생성과 에러 발생은 의미가
다르다.

에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.

throw 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정한다. 에러를 던지면 catch 문의 에러 변수가
생성되고 던져진 에러 객체가 할당된다. 그리고 catch 코드 블록이 실행되기 시작한다. -->

<!-- 47.5 에러의 전파 -->

<!-- 에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행
컨텍스트 방향)으로 전파된다. -->